### ISSUE TITLE
Missing tests/data?

### ISSUE THREAD

**Issue by aking7** [fhchl/pimp#1]
It builds! But I think I'm missing the tests/data folder. From the `make test` log:

`error: Error when opening ../tests/data/sweep.wav [errno 2: No such file or directory]`

![image](https://user-images.githubusercontent.com/10705652/149405755-07e5bb25-7574-4300-8ad6-3049d591db75.png)

[LastTest.log](https://github.com/fhchl/pimp/files/7865840/LastTest.log)

**Comment by fhchl** [comment]
Oh. I forgot that the testing is not fully automatic. The `make_wavs.py` script should make those test files, but I can see that it is using some of my personal libs. Will have a look on if those can be remove.

**Comment by fhchl** [comment]
I removed unnecessary tests and rewrote the python script to only require `numpy` and `scipy`. The script now runs when explicitly requesting building of the tests (see updated readme). @aking7, could you have another try and let me know how it goes on your machine?
